### ISSUE TITLE
Demo time checklist

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#85]
Spec:
- [x] Rebase components on Catalina doc: https://www.figma.com/file/Y9ByI8lazsLSfg3XqYGOKj/macOS-Components-%E2%80%93-Catalina?node-id=7%3A1788
- [x] Implement label components: 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/103326/73959785-29eb2b80-490a-11ea-95cb-758f9e15a98a.png">

- [ ] Fix button text size
- [ ] Fix checkbox text size
- [ ] Use single line mode on textfield
- [x] Fix radio button cut off geometry
- [x] Don't use custom fonts anywhere

Extension:

- [x] Fix content not being added to window and fix junk classes being generated: https://www.figma.com/file/zV2VF7tEdzCJL2CRo6pprz/Breakpoints?node-id=0%3A1
- [x] Use Document Title in solution nodes instead of the ID
- [x] Document Title in manifest.json and use for autogeneration comment
- [x] Use document version in autogeneration comment (or date if no label)
- [x] Use namespace of the current app. (or at least use "Figma" instead of "FigmaSharp" to avoid conflicts)
- [x] Only create classes for groups of type FRAME at the top level of the document
- [x] Remove layers starting with "# " or "// " from the .json

Sample app:
- [ ] Fix beachballing (UI freezes)
- [x] Fix "double" drawing of images on top of native controls

**Comment by hbons** [comment]
Closing this. I've created separate issues for the remaining items.
